"""
train_model.py
══════════════
Trains a Random Forest classifier on speech features to predict
speech quality: Poor (0) / Average (1) / Good (2).

Steps:
  1. Load dataset.csv  (generated by generate_dataset.py)
  2. Train/test split  (80/20, stratified)
  3. Scale features    (StandardScaler)
  4. Train RandomForestClassifier (n_estimators=100)
  5. Print accuracy, classification report, confusion matrix
  6. Save model + scaler to model.pkl
  7. Plot confusion matrix and feature importance charts

Usage:
    python train_model.py
    python train_model.py --dataset my_data.csv --trees 200
"""

import os
import argparse
import numpy as np
import pandas as pd
import joblib
import matplotlib
matplotlib.use('Agg')   # non-interactive backend — works without a display
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble          import RandomForestClassifier
from sklearn.model_selection   import train_test_split, cross_val_score
from sklearn.preprocessing     import StandardScaler
from sklearn.metrics           import (
    accuracy_score, classification_report,
    confusion_matrix, ConfusionMatrixDisplay,
)

from extract_features import FEATURE_NAMES

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
DATASET_CSV = os.path.join(BASE_DIR, "dataset.csv")
MODEL_PKL   = os.path.join(BASE_DIR, "model.pkl")
CM_PNG      = os.path.join(BASE_DIR, "confusion_matrix.png")
FI_PNG      = os.path.join(BASE_DIR, "feature_importance.png")

CLASS_NAMES = ["Poor", "Average", "Good"]


def train(dataset_path: str = DATASET_CSV, n_trees: int = 100) -> None:

    # ── 1. Load data ──────────────────────────────────────────────────────────
    print(f"\n{'='*55}")
    print("  VOXIRA — Speech Quality Random Forest Training")
    print(f"{'='*55}\n")

    if not os.path.exists(dataset_path):
        print(f"[Train] dataset.csv not found at {dataset_path}")
        print("[Train] Generating synthetic dataset first…")
        from generate_dataset import generate_dataset
        df = generate_dataset(300)
        df.to_csv(dataset_path, index=False)
    else:
        df = pd.read_csv(dataset_path)

    print(f"[Train] Loaded {len(df)} samples from {dataset_path}")
    print(f"[Train] Class distribution:")
    dist = df['label'].value_counts().sort_index()
    for lbl, cnt in dist.items():
        print(f"         {CLASS_NAMES[lbl]:10s}: {cnt} samples")

    # ── 2. Feature matrix + labels ────────────────────────────────────────────
    missing = [f for f in FEATURE_NAMES if f not in df.columns]
    if missing:
        raise ValueError(f"Missing feature columns: {missing}")

    X = df[FEATURE_NAMES].values.astype(np.float32)
    y = df["label"].values.astype(int)

    # ── 3. Train / test split (stratified 80/20) ──────────────────────────────
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    print(f"\n[Train] Train samples : {len(X_train)}")
    print(f"[Train] Test  samples : {len(X_test)}")

    # ── 4. Feature scaling ────────────────────────────────────────────────────
    scaler  = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test  = scaler.transform(X_test)

    # ── 5. Train Random Forest ────────────────────────────────────────────────
    print(f"\n[Train] Training RandomForestClassifier (n_estimators={n_trees})…")
    clf = RandomForestClassifier(
        n_estimators     = n_trees,
        max_depth        = None,
        min_samples_split= 4,
        min_samples_leaf = 2,
        max_features     = "sqrt",
        class_weight     = "balanced",
        random_state     = 42,
        n_jobs           = -1,
    )
    clf.fit(X_train, y_train)
    print("[Train] Training complete.")

    # ── 6. Evaluate ───────────────────────────────────────────────────────────
    y_pred = clf.predict(X_test)
    acc    = accuracy_score(y_test, y_pred)

    print(f"\n{'─'*55}")
    print(f"  TEST ACCURACY : {acc * 100:.2f}%")
    print(f"{'─'*55}\n")

    print("Classification Report:")
    print(classification_report(y_test, y_pred, target_names=CLASS_NAMES))

    # 5-fold cross-validation on full dataset
    X_all_scaled = scaler.transform(X)
    cv_scores = cross_val_score(clf, X_all_scaled, y, cv=5, scoring="accuracy")
    print(f"5-Fold Cross-Validation Accuracy: "
          f"{cv_scores.mean()*100:.2f}% ± {cv_scores.std()*100:.2f}%")

    # ── 7. Confusion matrix ───────────────────────────────────────────────────
    cm = confusion_matrix(y_test, y_pred)
    print(f"\nConfusion Matrix:\n{cm}")

    fig, ax = plt.subplots(figsize=(7, 5))
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Blues",
        xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
        ax=ax, linewidths=0.5,
    )
    ax.set_xlabel("Predicted Label", fontsize=12)
    ax.set_ylabel("True Label", fontsize=12)
    ax.set_title(
        f"Random Forest — Confusion Matrix\nAccuracy: {acc*100:.2f}%",
        fontsize=13, fontweight="bold",
    )
    plt.tight_layout()
    plt.savefig(CM_PNG, dpi=150)
    plt.close()
    print(f"\n[Train] Confusion matrix saved → {CM_PNG}")

    # ── 8. Feature importance ─────────────────────────────────────────────────
    importances = clf.feature_importances_
    indices     = np.argsort(importances)[::-1]
    sorted_names = [FEATURE_NAMES[i] for i in indices]
    sorted_imp   = importances[indices]

    print("\nFeature Importances (top to bottom):")
    for name, imp in zip(sorted_names, sorted_imp):
        bar = "█" * int(imp * 60)
        print(f"  {name:25s} {imp:.4f}  {bar}")

    fig2, ax2 = plt.subplots(figsize=(9, 5))
    colors = plt.cm.viridis(np.linspace(0.2, 0.9, len(sorted_names)))
    bars = ax2.barh(sorted_names[::-1], sorted_imp[::-1], color=colors[::-1])
    ax2.set_xlabel("Feature Importance (Gini)", fontsize=12)
    ax2.set_title(
        "Random Forest — Feature Importance\nVoxira Speech Quality Model",
        fontsize=13, fontweight="bold",
    )
    ax2.bar_label(bars, fmt="%.3f", padding=3, fontsize=9)
    plt.tight_layout()
    plt.savefig(FI_PNG, dpi=150)
    plt.close()
    print(f"[Train] Feature importance chart saved → {FI_PNG}")

    # ── 9. Save model ─────────────────────────────────────────────────────────
    payload = {
        "model":         clf,
        "scaler":        scaler,
        "feature_names": FEATURE_NAMES,
        "class_names":   CLASS_NAMES,
        "accuracy":      acc,
        "cv_mean":       cv_scores.mean(),
        "cv_std":        cv_scores.std(),
        "n_trees":       n_trees,
        "n_train":       len(X_train),
    }
    joblib.dump(payload, MODEL_PKL)
    print(f"\n[Train] Model saved → {MODEL_PKL}")

    print(f"\n{'='*55}")
    print(f"  TRAINING COMPLETE")
    print(f"  Accuracy : {acc*100:.2f}%")
    print(f"  CV Score : {cv_scores.mean()*100:.2f}% ± {cv_scores.std()*100:.2f}%")
    print(f"  Model    : {MODEL_PKL}")
    print(f"{'='*55}\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", default=DATASET_CSV)
    parser.add_argument("--trees",   type=int, default=100)
    args = parser.parse_args()
    train(args.dataset, args.trees)
